global using System.Diagnostics;
global using System.ComponentModel.DataAnnotations;
global using Arretadinhos.Models;
global using Arretadinhos.Models.Enums;
global using Arretadinhos.Models.ViewModels;
global using Arretadinhos.Services;
global using Arretadinhos.Services.Exceptions;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;